### ISSUE TITLE
Unable to open apk file

### ISSUE THREAD

**Issue by FTno** [apk-spectrum/apk-scanner#1]
APK Scanner is not able to open the apk file downloaded from here: https://apkpure.com/appbrain-ad-detector/com.appspot.swisscodemonkeys.detector
(AppBrain Ad Detector_v2.5_apkpure.com.apk)

I have tried to open the file in APK Scanner on both a Windows computer and one with Linux.

APK Scanner has succeeded in opening all the other apk files I have tried to open.

Thanks for a useful program.

**Comment by sunggyu-kam** [comment]
This issue was already fixed that 736394b728c49e055d1bb7a79b94df7b784db597.

I will release with this issue and other improved features within a few weeks.
If you want to check it a little earlier,
Download the ApkScanner.jar file from the [v2.4.2_hotfix#1](https://github.com/apk-spectrum/apk-scanner/releases/tag/v2.4.2_hotfix%231) tag and overwrite the installation path.

Thank you for your attention.

**Comment by FTno** [comment]
Can confirm that the hotfix works.
Thanks for fixing.
